vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    
    mappings:
        teacher_image:
            # uri_prefix: /images/teacher
            uri_prefix: '/images/teacher'
            upload_destination: '%kernel.project_dir%/public/images/teachers'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
        course_image:
            uri_prefix: '/images/courses'
            upload_destination: '%kernel.project_dir%/public/images/courses'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            # inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
            
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
